---
- name: Sudo | Ensure sudo is installed
  apt:
    name: sudo
    state: present
  when: ansible_distribution ==  'Debian' or ansible_distribution == 'Ubuntu'

- name: Sudo | Ensure sudo is installed
  yum:
    name: sudo
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Sudo | Copy default sudoers file to /etc/sudoers
  template:
    src: etc_sudoers
    dest: /etc/sudoers
    mode: 440
    owner: root
    group: root
    validate: 'visudo -cf %s'
  when: sudo_set_custom_commands is not defined

- name: Sudo | Copy custom command sudoers file to /etc/sudoers
  template:
    src: etc_sudoers_custom
    dest: /etc/sudoers
    mode: 440
    owner: root
    group: root
    validate: 'visudo -cf %s'
  when: sudo_set_custom_commands is defined and sudo_set_per_user is iterable

- name: Sudo | Create sudoers file per user
  template:
    src: etc_sudoers_per_user
    dest: "/etc/sudoers.d/{{ item }}"
    mode: 440
    owner: root
    group: root
    validate: 'visudo -cf %s'
  when: sudo_set_per_user is defined and sudo_set_per_user is iterable
  loop: "{{ sudo_set_per_user }}"
